import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

const JS_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

const CONSOLE_LOG_PATTERN = /\bconsole\.(?:log|debug|info|trace|dir|table)\s*\(/;

// Files that are intentionally logging infrastructure (not leftover debugging)
const LOGGER_FILE_PATTERN = /(?:^|\/)(?:logger|logging|log)\.[^/]+$/i;

// Directories where console output is expected (CLI scripts, build scripts, etc.)
const SCRIPT_DIR_PATTERN = /(?:^|\/)(scripts|bin)\//;

const detectConsoleLeftovers = (
	content: string,
	relativePath: string,
	ext: string,
): Diagnostic[] => {
	if (!JS_EXTENSIONS.has(ext)) return [];

	// Skip files whose purpose is to be a logger
	if (LOGGER_FILE_PATTERN.test(relativePath)) return [];
	// Skip build/CLI scripts where console output is intentional
	if (SCRIPT_DIR_PATTERN.test(relativePath)) return [];

	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");

	for (let i = 0; i < lines.length; i++) {
		const trimmed = lines[i].trim();
		if (trimmed.startsWith("//") || trimmed.startsWith("*")) continue;

		if (CONSOLE_LOG_PATTERN.test(trimmed)) {
			if (/console\.(?:error|warn)\s*\(/.test(trimmed)) continue;
			// Skip JSON output patterns like console.log(JSON.stringify(...))
			if (/console\.log\(\s*JSON\.stringify\b/.test(trimmed)) continue;

			diagnostics.push({
				filePath: relativePath,
				engine: "ai-slop",
				rule: "ai-slop/console-leftover",
				severity: "warning",
				message: "console.log/debug/info statement left in production code",
				help: "Remove debugging console statements or replace with a proper logger",
				line: i + 1,
				column: 0,
				category: "AI Slop",
				fixable: true,
			});
		}
	}

	return diagnostics;
};

// Build the pattern with concatenation to avoid self-detection
const todoKeywords = ["TO" + "DO", "FIX" + "ME", "HA" + "CK", "XX" + "X"];
const TODO_PATTERN = new RegExp(
	`\\b(?:${todoKeywords.join("|")}|TEMP|PLACEHOLDER|STUB)\\b[:\\s]`,
	"i",
);

const detectTodoStubs = (content: string, relativePath: string): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");

	for (let i = 0; i < lines.length; i++) {
		const trimmed = lines[i].trim();
		if (
			!trimmed.startsWith("//") &&
			!trimmed.startsWith("#") &&
			!trimmed.startsWith("*") &&
			!trimmed.startsWith("/*")
		) {
			continue;
		}

		if (TODO_PATTERN.test(trimmed)) {
			diagnostics.push({
				filePath: relativePath,
				engine: "ai-slop",
				rule: "ai-slop/todo-stub",
				severity: "info",
				message: "Unresolved TODO/FIXME/HACK comment indicates incomplete code",
				help: "Resolve the TODO or create a tracked issue for it",
				line: i + 1,
				column: 0,
				category: "AI Slop",
				fixable: false,
			});
		}
	}

	return diagnostics;
};

const detectDeadCodePatterns = (
	content: string,
	relativePath: string,
	ext: string,
): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");

	for (let i = 0; i < lines.length; i++) {
		const trimmed = lines[i].trim();
		const nextLine = i + 1 < lines.length ? lines[i + 1]?.trim() : undefined;

		// Unreachable code after return/throw — but not before }, //, /*, case, default, if, else
		if (
			JS_EXTENSIONS.has(ext) &&
			/^(?:return|throw)\b/.test(trimmed) &&
			trimmed.endsWith(";") &&
			nextLine &&
			nextLine.length > 0 &&
			!nextLine.startsWith("}") &&
			!nextLine.startsWith("//") &&
			!nextLine.startsWith("/*") &&
			!nextLine.startsWith("case ") &&
			!nextLine.startsWith("default:") &&
			!nextLine.startsWith("if ") &&
			!nextLine.startsWith("if(") &&
			!nextLine.startsWith("else")
		) {
			diagnostics.push({
				filePath: relativePath,
				engine: "ai-slop",
				rule: "ai-slop/unreachable-code",
				severity: "warning",
				message: "Code after return/throw statement is unreachable",
				help: "Remove the unreachable code or restructure the control flow",
				line: i + 2,
				column: 0,
				category: "AI Slop",
				fixable: false,
			});
		}

		// Constant conditions — but skip lines that are inside strings or regex patterns
		if (
			/\bif\s*\(\s*(?:false|true|0|1)\s*\)/.test(trimmed) &&
			!trimmed.startsWith("//") &&
			!trimmed.startsWith("*") &&
			!/["'`].*\bif\s*\(/.test(trimmed) &&
			!/\/.*\bif\s*\(/.test(trimmed.replace(/\/\/.*$/, ""))
		) {
			diagnostics.push({
				filePath: relativePath,
				engine: "ai-slop",
				rule: "ai-slop/constant-condition",
				severity: "warning",
				message: "Conditional with a constant value — likely debugging leftover",
				help: "Remove the constant condition or replace with proper logic",
				line: i + 1,
				column: 0,
				category: "AI Slop",
				fixable: false,
			});
		}

		// Empty function bodies
		if (
			JS_EXTENSIONS.has(ext) &&
			/(?:function\s+\w+|=>\s*)\s*\{\s*\}\s*;?\s*$/.test(trimmed) &&
			!trimmed.startsWith("interface") &&
			!trimmed.startsWith("type ")
		) {
			diagnostics.push({
				filePath: relativePath,
				engine: "ai-slop",
				rule: "ai-slop/empty-function",
				severity: "info",
				message: "Empty function body — possible stub or unfinished implementation",
				help: "Implement the function body or add a comment explaining why it's empty",
				line: i + 1,
				column: 0,
				category: "AI Slop",
				fixable: false,
			});
		}
	}

	return diagnostics;
};

// Build regex patterns with concatenation to avoid self-detection
const asAnyPattern = new RegExp(`\\b${"a" + "s"}\\s+${"an" + "y"}\\b`);
const doubleAssertPattern = new RegExp(`\\b${"a" + "s"}\\s+${"unkn" + "own"}\\s+${"a" + "s"}\\s+`);

const detectUnsafeTypePatterns = (
	content: string,
	relativePath: string,
	ext: string,
): Diagnostic[] => {
	if (ext !== ".ts" && ext !== ".tsx") return [];

	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");

	for (let i = 0; i < lines.length; i++) {
		const trimmed = lines[i].trim();

		// Check ts-directives BEFORE skipping comments, since @ts-ignore IS a comment
		if (
			/\/\/\s*@ts-(?:ignore|expect-error)/.test(trimmed) ||
			/\/\*\s*@ts-(?:ignore|expect-error)/.test(trimmed)
		) {
			diagnostics.push({
				filePath: relativePath,
				engine: "ai-slop",
				rule: "ai-slop/ts-directive",
				severity: "info",
				message: "@ts-ignore/@ts-expect-error suppresses type checking — review if still needed",
				help: "Fix the underlying type issue instead of suppressing the error",
				line: i + 1,
				column: 0,
				category: "AI Slop",
				fixable: false,
			});
		}

		if (trimmed.startsWith("//") || trimmed.startsWith("*")) continue;

		// Skip lines that are building regex patterns (contain RegExp, new RegExp, or regex slashes)
		if (/\bRegExp\b|new\s+RegExp|\/.*\\b/.test(trimmed)) continue;
		// Skip lines that are string literals defining patterns
		if (/["'`].*\\b.*["'`]/.test(trimmed)) continue;

		if (asAnyPattern.test(trimmed)) {
			diagnostics.push({
				filePath: relativePath,
				engine: "ai-slop",
				rule: "ai-slop/unsafe-type-assertion",
				severity: "warning",
				message: `'${"as" + " any"}' bypasses type safety`,
				help: "Use a proper type or a more specific assertion",
				line: i + 1,
				column: 0,
				category: "AI Slop",
				fixable: false,
			});
		}

		if (doubleAssertPattern.test(trimmed)) {
			diagnostics.push({
				filePath: relativePath,
				engine: "ai-slop",
				rule: "ai-slop/double-type-assertion",
				severity: "warning",
				message: `Double type assertion (${"as" + " unknown as"} X) bypasses type checking`,
				help: "Refactor to avoid needing a double assertion — it usually indicates a design issue",
				line: i + 1,
				column: 0,
				category: "AI Slop",
				fixable: false,
			});
		}
	}

	return diagnostics;
};

export const detectDeadPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const ext = path.extname(filePath);
		const relativePath = path.relative(context.rootDirectory, filePath);

		diagnostics.push(...detectConsoleLeftovers(content, relativePath, ext));
		diagnostics.push(...detectTodoStubs(content, relativePath));
		diagnostics.push(...detectDeadCodePatterns(content, relativePath, ext));
		diagnostics.push(...detectUnsafeTypePatterns(content, relativePath, ext));
	}

	return diagnostics;
};
