import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

const RUST_EXTENSIONS = new Set([".rs"]);

const UNWRAP_CALL_RE = /\.unwrap\s*\(\s*\)/;
const TODO_MACRO_RE = /\b(todo|unimplemented)\s*!\s*\(/;
const COMMENT_LINE_RE = /^\s*\/\//;
const TEST_ATTR_RE = /^\s*#\s*\[\s*(?:cfg\s*\(\s*test\s*\)|test|tokio::test)/;

const isTestFile = (relPath: string): boolean => {
	const segments = relPath.split(path.sep);
	if (segments.includes("tests")) return true;
	const basename = segments[segments.length - 1] ?? "";
	return basename === "tests.rs" || basename.endsWith("_tests.rs");
};

// Walk the file: track whether we're inside a `#[cfg(test)]` mod block. Lines inside
// that block (or inside any `#[test]`-attributed item) are exempt from unwrap noise.
const buildTestRanges = (lines: string[]): Array<[number, number]> => {
	const ranges: Array<[number, number]> = [];
	for (let i = 0; i < lines.length; i++) {
		if (!TEST_ATTR_RE.test(lines[i])) continue;
		// Find the next `{` and walk to its matching `}`.
		const openLine = i;
		let depth = 0;
		let started = false;
		for (let j = i; j < lines.length; j++) {
			const line = lines[j];
			for (const ch of line) {
				if (ch === "{") {
					depth++;
					started = true;
				} else if (ch === "}") depth--;
			}
			if (started && depth === 0) {
				ranges.push([openLine, j]);
				i = j;
				break;
			}
		}
	}
	return ranges;
};

const isInRange = (ranges: Array<[number, number]>, lineIdx: number): boolean =>
	ranges.some(([start, end]) => lineIdx >= start && lineIdx <= end);

const flagNonTestUnwrap = (
	lines: string[],
	relPath: string,
	testRanges: Array<[number, number]>,
	out: Diagnostic[],
): void => {
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (COMMENT_LINE_RE.test(line)) continue;
		if (isInRange(testRanges, i)) continue;
		if (!UNWRAP_CALL_RE.test(line)) continue;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/rust-non-test-unwrap",
			severity: "warning",
			message:
				"`.unwrap()` in non-test code panics on None/Err. Surfaces as a hard crash for the caller.",
			help: 'Use `?` to propagate, `.expect("context")` if you really mean it (and the message names the invariant), or pattern-match the variant you care about. Reserve raw `.unwrap()` for tests and prototypes.',
			line: i + 1,
			column: 1,
			category: "AI Slop",
			fixable: false,
		});
	}
};

const flagTodoMacro = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (COMMENT_LINE_RE.test(line)) continue;
		const match = TODO_MACRO_RE.exec(line);
		if (!match) continue;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/rust-todo-stub",
			severity: "warning",
			message: `\`${match[1]}!()\` panics at runtime — almost certainly a stub the agent forgot to fill in.`,
			help: "Implement the missing path or remove it. If the work is genuinely deferred, file a ticket and put the number in a comment next to the macro so it doesn't ship invisibly.",
			line: i + 1,
			column: 1,
			category: "AI Slop",
			fixable: false,
		});
	}
};

export const detectRustPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);

	for (const filePath of files) {
		if (!RUST_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const relPath = path.relative(context.rootDirectory, filePath);
		const lines = content.split("\n");

		// Whole-file test mode: skip unwrap-checking, still flag todo!() (those are bugs anywhere).
		if (isTestFile(relPath)) {
			flagTodoMacro(lines, relPath, diagnostics);
			continue;
		}

		const testRanges = buildTestRanges(lines);
		flagNonTestUnwrap(lines, relPath, testRanges, diagnostics);
		flagTodoMacro(lines, relPath, diagnostics);
	}

	return diagnostics;
};
