import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getTestFiles, isAutoGenerated } from "../../utils/source-files.js";
import { maskStringsAndComments } from "../../utils/source-masker.js";
import type { Diagnostic, EngineContext } from "../types.js";

const JS_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

const JS_TAUTOLOGY_PATTERNS = [
	/\bexpect\s*\(\s*(true|false|-?\d+(?:\.\d+)?)\s*\)\s*\.\s*toBe\s*\(\s*\1\s*\)/,
	/\bassert\s*\.\s*(?:equal|strictEqual)\s*\(\s*(true|false|-?\d+(?:\.\d+)?)\s*,\s*\1\s*\)/,
];
const PYTHON_TAUTOLOGY_RE = /^\s*assert\s+True\b/;

const isTautologicalLine = (line: string, extension: string): boolean => {
	if (extension === ".py") return PYTHON_TAUTOLOGY_RE.test(line);
	if (!JS_EXTENSIONS.has(extension)) return false;
	return JS_TAUTOLOGY_PATTERNS.some((pattern) => pattern.test(line));
};

export const detectTautologicalTests = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	for (const filePath of getTestFiles(context)) {
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const extension = path.extname(filePath).toLowerCase();
		const lines = maskStringsAndComments(content, extension).split("\n");
		for (let index = 0; index < lines.length; index++) {
			if (!isTautologicalLine(lines[index], extension)) continue;
			diagnostics.push({
				filePath: relativePosix(context.rootDirectory, filePath),
				engine: "ai-slop",
				rule: "ai-slop/tautological-test",
				severity: "warning",
				message: "Tautological test assertion cannot fail",
				help: "Assert behavior produced by the code under test instead of comparing fixed literals.",
				line: index + 1,
				column: 1,
				category: "AI Slop",
				fixable: false,
			});
		}
	}
	return diagnostics;
};
