import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

interface FunctionInfo {
	name: string;
	startLine: number;
	lineCount: number;
	maxNesting: number;
	paramCount: number;
}
interface FunctionPattern {
	regex: RegExp;
	langFilter: string[];
}

const FUNCTION_PATTERNS: FunctionPattern[] = [
	{
		regex: /^\s*(?:export\s+)?(?:async\s+)?function\s+(\w+)\s*\(([^)]*)\)/,
		langFilter: [".js", ".ts", ".jsx", ".tsx", ".mjs", ".cjs"],
	},
	{
		regex: /^\s*(?:export\s+)?const\s+(\w+)\s*=\s*(?:async\s+)?\(([^)]*)\)\s*(?:=>|:\s*\w)/,
		langFilter: [".js", ".ts", ".jsx", ".tsx", ".mjs", ".cjs"],
	},
	{
		regex: /^\s*def\s+(\w+)\s*\(([^)]*)\)/,
		langFilter: [".py"],
	},
	{
		regex: /^\s*func\s+(?:\([^)]*\)\s+)?(\w+)\s*\(([^)]*)\)/,
		langFilter: [".go"],
	},
	{
		regex: /^\s*fn\s+(\w+)\s*\(([^)]*)\)/,
		langFilter: [".rs"],
	},
	{
		regex: /^\s*(?:public|private|protected)?\s*(?:static\s+)?(?:\w+\s+)(\w+)\s*\(([^)]*)\)/,
		langFilter: [".java", ".cs", ".cpp", ".c", ".php"],
	},
];

const countParams = (p: string): number => (p.trim() ? p.split(",").length : 0);

const matchFunctionOnLine = (
	line: string,
	ext: string,
): { name: string; params: string; patternIndex: number } | null => {
	for (let i = 0; i < FUNCTION_PATTERNS.length; i++) {
		const pattern = FUNCTION_PATTERNS[i];
		if (!pattern.langFilter.includes(ext)) continue;
		const match = line.match(pattern.regex);
		if (match) return { name: match[1], params: match[2] ?? "", patternIndex: i };
	}
	return null;
};

const PYTHON_CONTROL_FLOW_RE = /^\s*(?:if|for|while|with|try|except|else|elif|finally|def|class)\b/;

const findFunctionEnd = (
	lines: string[],
	startIndex: number,
	isPython: boolean,
): { endLine: number; maxNesting: number } => {
	if (isPython) {
		return findPythonFunctionEnd(lines, startIndex);
	}
	return findBraceFunctionEnd(lines, startIndex);
};

// Check if a `{` at a given position is a control-flow brace (not an object literal)
const isControlFlowBrace = (lineText: string, braceIndex: number): boolean => {
	const before = lineText.substring(0, braceIndex).trimEnd();
	// After `)` — if/for/while/switch/catch/function params/callback
	if (before.endsWith(")")) return true;
	// After `=>` — arrow function body
	if (before.endsWith("=>")) return true;
	// After `else`, `try`, `finally`, `do`
	if (/\b(?:else|try|finally|do)$/.test(before)) return true;
	return false;
};

const findBraceFunctionEnd = (
	lines: string[],
	startIndex: number,
): { endLine: number; maxNesting: number } => {
	let depth = 0;
	let started = false;
	let endLine = startIndex;
	let maxNesting = 0;
	let functionStartDepth = 0;
	// Stack tracking whether each open brace is control-flow (true) or data (false)
	const braceStack: boolean[] = [];

	for (let j = startIndex; j < lines.length; j++) {
		const l = lines[j];

		for (let ci = 0; ci < l.length; ci++) {
			const ch = l[ci];
			if (ch === "{") {
				depth++;
				if (!started) {
					started = true;
					functionStartDepth = depth;
					braceStack.push(false); // function body brace itself
				} else {
					const isCF = isControlFlowBrace(l, ci);
					braceStack.push(isCF);
					if (isCF) {
						let cfCount = 0;
						for (const b of braceStack) {
							if (b) cfCount++;
						}
						if (cfCount > maxNesting) maxNesting = cfCount;
					}
				}
			} else if (ch === "}") {
				depth--;
				braceStack.pop();
			}
		}

		if (started && depth < functionStartDepth && j > startIndex) {
			endLine = j;
			break;
		}

		if (j === lines.length - 1) endLine = j;
	}

	// No opening brace found — braceless arrow function (single expression)
	if (!started) return { endLine: startIndex, maxNesting: 0 };

	return { endLine, maxNesting };
};

const findPythonFunctionEnd = (
	lines: string[],
	startIndex: number,
): { endLine: number; maxNesting: number } => {
	const startLine = lines[startIndex];
	const baseIndent = startLine.match(/^(\s*)/)?.[1].length ?? 0;
	let endLine = startIndex;
	let maxNesting = 0;
	// Track control-flow nesting depth via a stack of indent levels
	const controlIndentStack: number[] = [];

	for (let j = startIndex + 1; j < lines.length; j++) {
		const l = lines[j];
		// Skip blank lines
		if (l.trim() === "") {
			endLine = j;
			continue;
		}

		const currentIndent = l.match(/^(\s*)/)?.[1].length ?? 0;

		// If we've returned to or past the base indent, function ended
		if (currentIndent <= baseIndent) {
			break;
		}

		endLine = j;

		// Pop any control-flow levels that we've exited
		while (
			controlIndentStack.length > 0 &&
			currentIndent <= controlIndentStack[controlIndentStack.length - 1]
		) {
			controlIndentStack.pop();
		}

		// If this line starts with a control-flow keyword, push its indent
		if (PYTHON_CONTROL_FLOW_RE.test(l)) {
			controlIndentStack.push(currentIndent);
			const nesting = controlIndentStack.length;
			if (nesting > maxNesting) maxNesting = nesting;
		}
	}

	return { endLine, maxNesting };
};

const isDataFile = (content: string): boolean => {
	const lines = content.split("\n");
	const nonEmpty = lines.filter((l) => l.trim().length > 0);
	if (nonEmpty.length === 0) return false;
	const dataLinePattern = /^\s*[{}[\]"']/;
	const dataLines = nonEmpty.filter((l) => dataLinePattern.test(l));
	return dataLines.length / nonEmpty.length > 0.8;
};

// Patterns for isBlockArrow — kept at module level to avoid brace
// characters inside the function body confusing the naive brace counter.
const ARROW_BLOCK_RE = new RegExp("=>\\s*\\{");
const ARROW_END_RE = new RegExp("=>\\s*$");
const BRACE_START_RE = new RegExp("^\\s*\\{");
const NEW_STATEMENT_RE = new RegExp("^(?:export\\s+)?(?:const|let|var|function|class)\\s");

// Check if an arrow function (pattern index 1) has a block body `=> {` vs expression `=> expr`
const isBlockArrow = (lines: string[], startIndex: number): boolean => {
	// Check the start line first
	if (ARROW_BLOCK_RE.test(lines[startIndex])) return true;

	// If the line ends with `=>`, check the next line
	if (ARROW_END_RE.test(lines[startIndex])) {
		const next = lines[startIndex + 1];
		if (next && BRACE_START_RE.test(next)) return true;
	}

	// If the arrow has a type annotation spanning multiple lines, check further
	// but stop at blank lines or new declarations
	for (let j = startIndex + 1; j < Math.min(startIndex + 3, lines.length); j++) {
		const l = lines[j];
		if (l.trim() === "" || NEW_STATEMENT_RE.test(l.trim())) break;
		if (ARROW_BLOCK_RE.test(l)) return true;
		if (BRACE_START_RE.test(l)) return true;
	}
	return false;
};

const analyzeFunctions = (content: string, ext: string): FunctionInfo[] => {
	const lines = content.split("\n");
	const functions: FunctionInfo[] = [];

	for (let i = 0; i < lines.length; i++) {
		const fnMatch = matchFunctionOnLine(lines[i], ext);
		if (!fnMatch) continue;

		const isPython = fnMatch.patternIndex === 2;

		// For arrow functions, skip single-expression (braceless) arrows
		if (fnMatch.patternIndex === 1 && !isBlockArrow(lines, i)) {
			continue;
		}

		const { endLine, maxNesting } = findFunctionEnd(lines, i, isPython);

		functions.push({
			name: fnMatch.name,
			startLine: i + 1,
			lineCount: endLine - i + 1,
			maxNesting,
			paramCount: countParams(fnMatch.params),
		});
	}

	return functions;
};

interface QualityLimits {
	maxFunctionLoc: number;
	maxFileLoc: number;
	maxNesting: number;
	maxParams: number;
}

const checkFileDiagnostics = (
	relativePath: string,
	content: string,
	limits: QualityLimits,
): Diagnostic[] => {
	const results: Diagnostic[] = [];
	const lineCount = content.split("\n").length;
	const ext = path.extname(relativePath).toLowerCase();

	// Skip data files entirely
	if (isDataFile(content)) return results;

	// Apply 2x threshold for JSX/TSX files
	const isJsx = ext === ".jsx" || ext === ".tsx";
	const effectiveMax = isJsx ? limits.maxFileLoc * 2 : limits.maxFileLoc;

	if (lineCount > effectiveMax) {
		results.push({
			filePath: relativePath,
			engine: "code-quality",
			rule: "complexity/file-too-large",
			severity: "warning",
			message: `File has ${lineCount} lines (max: ${effectiveMax})`,
			help: "Consider splitting this file into smaller modules",
			line: 0,
			column: 0,
			category: "Complexity",
			fixable: false,
		});
	}

	return results;
};

const checkFunctionDiagnostics = (
	relativePath: string,
	fn: FunctionInfo,
	limits: QualityLimits,
): Diagnostic[] => {
	const results: Diagnostic[] = [];

	if (fn.lineCount > limits.maxFunctionLoc) {
		results.push({
			filePath: relativePath,
			engine: "code-quality",
			rule: "complexity/function-too-long",
			severity: "warning",
			message: `Function '${fn.name}' has ${fn.lineCount} lines (max: ${limits.maxFunctionLoc})`,
			help: "Consider breaking this function into smaller pieces",
			line: fn.startLine,
			column: 0,
			category: "Complexity",
			fixable: false,
		});
	}

	if (fn.maxNesting > limits.maxNesting) {
		results.push({
			filePath: relativePath,
			engine: "code-quality",
			rule: "complexity/deep-nesting",
			severity: "warning",
			message: `Function '${fn.name}' has nesting depth ${fn.maxNesting} (max: ${limits.maxNesting})`,
			help: "Consider using early returns or extracting nested logic",
			line: fn.startLine,
			column: 0,
			category: "Complexity",
			fixable: false,
		});
	}

	if (fn.paramCount > limits.maxParams) {
		results.push({
			filePath: relativePath,
			engine: "code-quality",
			rule: "complexity/too-many-params",
			severity: "warning",
			message: `Function '${fn.name}' has ${fn.paramCount} parameters (max: ${limits.maxParams})`,
			help: "Consider using an options object parameter",
			line: fn.startLine,
			column: 0,
			category: "Complexity",
			fixable: false,
		});
	}

	return results;
};

const checkFileComplexity = (
	filePath: string,
	rootDirectory: string,
	limits: QualityLimits,
): Diagnostic[] => {
	let content: string;
	try {
		content = fs.readFileSync(filePath, "utf-8");
	} catch {
		return [];
	}

	const relativePath = path.relative(rootDirectory, filePath);
	const ext = path.extname(filePath).toLowerCase();
	const diagnostics = checkFileDiagnostics(relativePath, content, limits);

	for (const fn of analyzeFunctions(content, ext)) {
		diagnostics.push(...checkFunctionDiagnostics(relativePath, fn, limits));
	}

	return diagnostics;
};

export const checkComplexity = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const limits: QualityLimits = context.config.quality;
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		diagnostics.push(...checkFileComplexity(filePath, context.rootDirectory, limits));
	}

	return diagnostics;
};
